# Generated by Django 4.2.6 on 2023-10-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dishes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="default_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=38),
        ),
    ]
