# Generated by Django 4.2.6 on 2023-10-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dishes", "0002_alter_dish_default_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingridient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=38),
                ),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="dish",
            name="ingridients",
            field=models.ManyToManyField(to="dishes.ingridient"),
        ),
    ]
