# Generated by Django 4.2.6 on 2023-10-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dishes", "0003_ingridient_dish_ingridients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="ingridients",
            field=models.ManyToManyField(
                related_name="ingridients", to="dishes.ingridient"
            ),
        ),
    ]
